### PR TITLE
Query params not working #10

### LINKED ISSUE #10: Query params are not working
Query params need to be snake case to work and by convention are kebab case and access-key must be an option argument.

### PR DESCRIPTION
**Pull request by rafaeldelboni**
Changes the `req!` function to snake_case all keywords from `:query-params`
`req!` now accept a `options` map with `:access-key`

Closes #10

### CODE REVIEW

**Comment by lucasdf** [comment]
What about adding repl files to gitignore?

**Comment by lucasdf** [comment]
Also target directory

**Review by lucasdf — APPROVED** [review]
:boar!

**Comment by rafaeldelboni** [comment]
> :boar!

:its-so-fast:

**Pull request merged**
